name: check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Setup yarn
        run: yarn
      - name: Run yarn format
        run: |
          yarn nx run-many --target=check --all --verbose
          git diff --exit-code
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Setup yarn
        run: yarn
      - name: Run yarn lint
        run: |
          yarn nx run-many --target=lint --skip-nx-cache --verbose
