name: kubernetes-iac-testbed | integration-test

on:
  # TODO: remove
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kubernetes-iac-testbed.integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/helm/kind-action
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: yarn
        run: yarn
      # https://github.com/pulumi/setup-pulumi
      - name: Install pulumi CLI
        uses: pulumi/setup-pulumi@v2
        with:
          pulumi-version: 3.23.2
      - name: Setup pulumi cli
        run: |
          pulumi login --local
      - name: start
        run: |
          export PULUMI_CONFIG_PASSPHRASE=password
          npx nx run kubernetes-iac-testbed:start
