name: kubernetes-iac-testbed | integration-test

on:
  # TODO: remove
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["./kubernetes-iac-testbed"] }
    steps:
      - uses: actions/checkout@v2
      # https://github.com/helm/kind-action
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - uses: actions/setup-node@v2
        with:
          node-version-file: ${{ matrix.dir }}/.nvmrc
      - name: Setup pulumi
        uses: pulumi/actions@v3
        with:
          work-dir: ${{ matrix.dir }}
          command: preview
          stack-name: dev
          # Use local File System
          # https://github.com/pulumi/actions#pulumi---nodejs-runtime--local-file-system-self-managed-backend
          cloud-url: file://~
          upsert: true
        env:
          #PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: "password"
      - name: Run yarn start
        run: yarn start
        working-directory: ${{ matrix.dir }}
