name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["./kubernetes-iac-testbed"] }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ${{ matrix.dir }}/.nvmrc
      - name: Setup yarn
        run: yarn
        working-directory: ${{ matrix.dir }}
      - name: Run yarn format
        run: |
          yarn format
          git diff --exit-code
        working-directory: ${{ matrix.dir }}
